### ISSUE TITLE
dashboard_utils script failure

### ISSUE THREAD

**Issue by sharathmalladi** [microsoft/mwt-ds#140]
**Repro steps**:
Calling ExperimentationAzure python script fails in some cases.
**Exception trace**:
E:\work\dashboard_utils.py:54: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  for index, row in df.resample(ag[0]).agg({type+'_'+field : max if field == 'c' else sum for type in df_col for field in df_col[type]}).replace(np.nan, 0.0).iterrows():
Traceback (most recent call last):
  File "E:\work\ExperimentationAzure.py", line 144, in <module>
    dashboard_utils.output_dashboard_data(d, dashboard_file_path)
  File "E:\work\dashboard_utils.py", line 61, in output_dashboard_data
    f.write(json.dumps({"ts":index.strftime("%Y-%m-%dT%H:%M:%SZ"),"d":d})+'\n')
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Series' is not JSON serializable

**Comment by marco-rossi29** [comment]
Solved in PR #141
